# Generated by Django 3.1.5 on 2021-07-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneighbour', '0003_authorities_health_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='health',
            name='logo',
            field=models.ImageField(upload_to='health_logo/'),
        ),
    ]
