# Generated by Django 3.1.5 on 2021-07-26 10:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myneighbour', '0004_auto_20210725_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo_pic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='profile_pic/'),
        ),
    ]
