# Generated by Django 3.1.5 on 2021-07-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneighbour', '0005_auto_20210726_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='logo',
            field=models.ImageField(upload_to='health_logo/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
    ]
